# ===================================================================
# SERVER CONFIGURATION
# ===================================================================
server.port=8080
server.servlet.context-path=/

# ===================================================================
# APPLICATION NAME
# ===================================================================
spring.application.name=cms-course-management-system

# ===================================================================
# POSTGRESQL DATABASE CONFIGURATION
# ===================================================================
# Trỏ trực tiếp đến Database PostgreSQL (Mặc định port 5432)
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/cms_db
spring.datasource.username=postgres
spring.datasource.password=123456

# ===================================================================
# JPA / HIBERNATE CONFIGURATION
# ===================================================================
# Tự động cập nhật bảng trong DB theo Entity Java
spring.jpa.hibernate.ddl-auto=update

# Khai báo Dialect hỗ trợ PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Hiển thị và định dạng SQL ra Console để dễ debug
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true

jwt.secret-key=daylachuoimahoabimatrikkei0987654321dacbietracroi

app.jwt.expiration-in-ms=600000


logging.level.org.springframework.security=DEBUG
logging.level.com.cms=DEBUG